FROM node:16 as build-stage

WORKDIR /usr/src/app

COPY ./package.json .
COPY ./package-lock.json .

RUN npm install

COPY ./frontend/ .

ENV REACT_APP_BACKEND_URL=http://localhost:8080
RUN node -e "console.log(process.env.REACT_APP_BACKEND_URL)"

RUN npm run build

# ...

FROM nginx:1.25-alpine

COPY --from=build-stage /usr/src/app/build /usr/share/nginx/html


