name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]
  
jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-20.04
    env:
      MONGO_DB_PW: ${{secrets.MONGO_DB_PW}}
      MONGO_DB_USER: ${{secrets.MONGO_DB_USER}}
      SECRET: ${{secrets.SECRET}}
      
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install dependencies 
        run: npm install  

      - name: Check style
        run: npm run eslint    

      - name: build
        run: npm run build      

      - name: e2e tests
        uses: cypress-io/github-action@v5
        with:
          command: npm run test:e2e
          start: npm run start-test
          wait-on: http://localhost:3003

      - name: Render Deployment
        if: ${{ github.event_name == 'push' && github.ref_name == 'main' && !contains(join(github.event.commits.*.message),'#skip')}}
        run : curl https://api.render.com/deploy/srv-${{ secrets.RENDER_SERVICE_ID }}?key=${{ secrets.RENDER_API_KEY }}

      - name: Bump version and tag
        if: ${{ github.event_name == 'push' && github.ref_name == 'main' && !contains(join(github.event.commits.*.message),'#skip') }}
        uses: anothrNick/github-tag-action@1.67.0
        env: 
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          WITH_V: true
          DEFAULT_BRANCH: render_deployment

      - name:  success notification 
        uses: rjstone/discord-webhook-notify@v1
        if: ${{success()}}
        with: 
          severity: info
          details: test success
          webhookUrl: ${{secrets.DISCORD_WEBHOOK}}
      - name: failure notification
        uses: rjstone/discord-webhook-notify@v1
        if: ${{ failure()}} 
        with: 
          severity: error
          details: test failed
          webhookUrl: ${{secrets.DISCORD_WEBHOOK}}

        







